mongodb:
  image: mongo:latest
  container: mongodb
  ports:
    - "27017:27017"
  restart: always
  environment: 
    MONGO_INITDB_ROOT_USERNAME: LilNigga
    MONGO_INITDB_ROOT_PASSWORD: FATIHA01
  volumes:
    - mongodb_data:/data/db


services:
  gioco: 
    build: 
      context: ./gioco
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb+srv://LilNigga:FATIHA01@nigga.lyz9vda.mongodb.net/Niggas?retryWrites=true&w=majority
    volumes:
      - ./gioco/models/schema.js:/gioco/models/schema.js


volumes: 
  mongodb_data:
